### PR TITLE
Add choice for interface

### PR DESCRIPTION
**Pull request by AutinDroid**
Pick an interface, any interface...
Great tool BTW :D

### CODE REVIEW

**Comment by B4ckP0r7** [comment]
as i said on others issues, i'm working on it;  but aircrack and hostapd are not working;
i'll fix it as fast as i can.

**Comment by AutinDroid** [comment]
@B4ckP0r7 It's a pull request... I just added this feature.

**Comment by B4ckP0r7** [comment]
i know, but i just added this feature, i'll publish upgrades soon :)

**Comment by AutinDroid** [comment]
@B4ckP0r7 I'll start working on the problems and I'll try to add more features, as this tool has lots of potential

**Pull request merged**
